version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file: .env
    volumes:
      - ./data/mysql:/var/lib/mysql

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    env_file: .env
    volumes:
      - ./data/mongodb:/data/db
      - ./sample.json:/sample.json

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file: .env
    ports:
      - 8080:80
    depends_on:
      - db
